kind: Pod
apiVersion: v1
metadata:
  generateName: bashterminal-2-
  annotations:
    openshift.io/deployment-config.latest-version: '2'
    openshift.io/deployment-config.name: bashterminal
    openshift.io/deployment.name: bashterminal-2
    openshift.io/scc: anyuid
  selfLink: /api/v1/namespaces/2336003gproject/pods/bashterminal-2-xqh26
  resourceVersion: '117374880'
  name: bashterminal-2-xqh26
  uid: ff7ebd8c-655d-11eb-8408-ac1f6bba3f6e
  creationTimestamp: '2021-02-02T13:53:15Z'
  namespace: 2336003gproject
  ownerReferences:
    - apiVersion: v1
      kind: ReplicationController
      name: bashterminal-2
      uid: fe506d5e-655d-11eb-8408-ac1f6bba3f6e
      controller: true
      blockOwnerDeletion: true
  labels:
    app: bashTerminal
    deployment: bashterminal-2
    deploymentconfig: bashterminal
spec:
  nodeSelector:
    node-role.kubernetes.io/compute: 'true'
  restartPolicy: Always
  serviceAccountName: containerroot
  imagePullSecrets:
    - name: containerroot-dockercfg-khbrf
  priority: 0
  schedulerName: default-scheduler
  terminationGracePeriodSeconds: 30
  nodeName: idagpu-01.dcs.gla.ac.uk
  securityContext:
    seLinuxOptions:
      level: 's0:c17,c14'
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 2Gi
        requests:
          cpu: '1'
          memory: 2Gi
      terminationMessagePath: /dev/termination-log
      name: bash
      command:
        - sleep
      securityContext:
        capabilities:
          drop:
            - MKNOD
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: terminal-nfs-access
          mountPath: /nfs/
        - name: containerroot-token-mndl8
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: 'docker-registry.default.svc:5000/2336003gproject/is-tweetminer:latest'
      args:
        - 24h
  serviceAccount: containerroot
  volumes:
    - name: terminal-nfs-access
      persistentVolumeClaim:
        claimName: 2336003gvol1claim
    - name: containerroot-token-mndl8
      secret:
        secretName: containerroot-token-mndl8
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-02-02T14:53:44Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-02-02T14:53:57Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: null
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-02-02T13:53:15Z'
  hostIP: 130.209.249.131
  podIP: 10.130.0.228
  startTime: '2021-02-02T14:53:44Z'
  containerStatuses:
    - name: bash
      state:
        running:
          startedAt: '2021-02-02T14:53:57Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: 'docker-registry.default.svc:5000/2336003gproject/is-tweetminer:latest'
      imageID: >-
        docker-pullable://docker-registry.default.svc:5000/2336003gproject/is-tweetminer@sha256:7b052e72c87edc9a8282274be10920ed031d805f06a4b9f32373cedb020d7cd3
      containerID: >-
        docker://1a9a642d14decf9718252efdb3a131a4092ed4e152f0c8925b44c8e421f14305
  qosClass: Guaranteed
